In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../Assignment/Titanic.csv")
p = pd.read_csv("planets.csv")

In [3]:
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [4]:
#Q1
df[df['Age'] > 65][['Pclass', 'Name', 'Fare']]

     Pclass                                  Name     Fare
33        2                 Wheadon, Mr. Edward H  10.5000
96        1             Goldschmidt, Mr. George B  34.6542
116       3                  Connors, Mr. Patrick   7.7500
493       1               Artagaveytia, Mr. Ramon  49.5042
630       1  Barkworth, Mr. Algernon Henry Wilson  30.0000
672       2           Mitchell, Mr. Henry Michael  10.5000
745       1          Crosby, Capt. Edward Gifford  71.0000
851       3                   Svensson, Mr. Johan   7.7750

In [5]:
#Q2
df[~(df['Embarked'] == 'S')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
#Q3
df[(df['Age'] < 10) | (df['Age'] > 70)].shape[0]

67

In [7]:
df.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
605,606,0,3,"Lindell, Mr. Edvard Bengtsson",male,36.0,1,0,349910,15.55,NaN,S

In [23]:
#Q4
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [9]:
#Q5
df['travel_group'] = "alone"
df.loc[df['SibSp'] + df['Parch'] > 0, 'travel_group'] = "With family"
df['travel_group'].value_counts()

travel_group
alone          537
With family    354
Name: count, dtype: int64

In [10]:
df.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,travel_group
536,537,0,1,"Butt, Major. Archibald Willingham",male,45.0,0,0,113050,26.55,B38,S,alone

In [11]:
p.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [12]:
p.shape

(1035, 6)

In [14]:
# True wherever a value is missing
p.isnull().sum()

method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64

In [ ]:
# count the blanks in one column
df['Age'].isnull().sum()

np.int64(714)

In [17]:
p.dropna()

              method  number  orbital_period    mass  distance  year
0    Radial Velocity       1       269.30000   7.100     77.40  2006
1    Radial Velocity       1       874.77400   2.210     56.95  2008
2    Radial Velocity       1       763.00000   2.600     19.84  2011
3    Radial Velocity       1       326.03000  19.400    110.62  2007
4    Radial Velocity       1       516.22000  10.500    119.47  2009
..               ...     ...             ...     ...       ...   ...
640  Radial Velocity       1       111.70000   2.100     14.90  2009
641  Radial Velocity       1         5.05050   1.068     44.46  2013
642  Radial Velocity       1       311.28800   1.940     17.24  1999
649          Transit       1         2.70339   1.470    178.00  2013
784  Radial Velocity       3       580.00000   0.947    135.00  2012

[498 rows x 6 columns]

In [33]:
# drop only where mass is blank
p.dropna(subset = ['mass'])

              method  number  orbital_period    mass  distance  year
0    Radial Velocity       1         269.300   7.100     77.40  2006
1    Radial Velocity       1         874.774   2.210     56.95  2008
2    Radial Velocity       1         763.000   2.600     19.84  2011
3    Radial Velocity       1         326.030  19.400    110.62  2007
4    Radial Velocity       1         516.220  10.500    119.47  2009
..               ...     ...             ...     ...       ...   ...
784  Radial Velocity       3         580.000   0.947    135.00  2012
913  Radial Velocity       1         677.800  19.800       NaN  2007
914  Radial Velocity       1           6.958   0.340       NaN  2014
915  Radial Velocity       1           5.118   0.400       NaN  2014
916  Radial Velocity       1         121.710   1.540       NaN  2014

[513 rows x 6 columns]

In [34]:
# drop the damaged columns instead, and see which survive 
p.dropna(axis = 1)

               method  number  year
0     Radial Velocity       1  2006
1     Radial Velocity       1  2008
2     Radial Velocity       1  2011
3     Radial Velocity       1  2007
4     Radial Velocity       1  2009
...               ...     ...   ...
1030          Transit       1  2006
1031          Transit       1  2007
1032          Transit       1  2007
1033          Transit       1  2008
1034          Transit       1  2008

[1035 rows x 3 columns]

In [35]:
df.dropna(subset=['Embarked'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,travel_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,With family
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,With family
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,alone
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,With family
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,alone
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,alone
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,alone
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,With family
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,alone
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,alone

In [36]:
df.dropna(axis = 1)

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,travel_group
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500,With family
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833,With family
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250,alone
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000,With family
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500,alone
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000,alone
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000,alone
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500,With family
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000,alone
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500,alone

In [22]:
# mean and median of mass
print(p['mass'].mean())
print(p['mass'].median())

2.6381605847953216
1.26

In [23]:
p['mass'].fillna(0).isnull().sum()

np.int64(0)

In [24]:
# how many exact duplicate rows ?
print(df.duplicated().sum())
print(p.duplicated().sum())

0
4

In [26]:
p.shape

(1035, 6)

In [25]:
# show them
p.drop_duplicates()

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1031 rows x 6 columns]

In [ ]:
p.drop_duplicates(subset = ['method'], ignore_index = True)
# normally pandas keeps the index original after dropping any row, but after using "ignore_index = True" indexing is automatically adjusts itself

                          method  number  orbital_period  mass  distance  year
0                Radial Velocity       1      269.300000  7.10     77.40  2006
1                        Imaging       1             NaN   NaN     45.52  2005
2      Eclipse Timing Variations       1    10220.000000  6.05       NaN  2009
3                        Transit       1        1.508956   NaN       NaN  2008
4                     Astrometry       1      246.360000   NaN     20.77  2013
5      Transit Timing Variations       2      160.000000   NaN   2119.00  2011
6  Orbital Brightness Modulation       2        0.240104   NaN   1180.00  2011
7                   Microlensing       1             NaN   NaN       NaN  2008
8                  Pulsar Timing       3       25.262000   NaN       NaN  1992
9    Pulsation Timing Variations       1     1170.000000   NaN       NaN  2007