In [26]:
import numpy as np
import pandas as pd

In [27]:
titanic = pd.read_csv("../Assignment/Titanic.csv")
tip = pd.read_csv("tip.csv")

In [38]:
tip.groupby("day")["total_bill"].size()

day
Fri     19
Sat     87
Sun     76
Thur    62
Name: total_bill, dtype: int64

In [29]:
tip.groupby("day").size()

day
Fri     19
Sat     87
Sun     76
Thur    62
dtype: int64

In [30]:
tip

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [31]:
summary = tip.groupby('day').agg(
    bill_count = ('total_bill', 'size'),
    avg_bill = ('total_bill', 'mean'),
    avg_tip = ('tip', 'mean')
).round(2)
summary

      bill_count  avg_bill  avg_tip
day
Fri           19     17.15     2.73
Sat           87     20.44     2.99
Sun           76     21.41     3.26
Thur          62     17.68     2.77

In [32]:
# Aggregate Function 
summary = tip.groupby("day").agg(
    bill_count = ("total_bill", 'size'),
    avg_bill = ("total_bill", "mean"),
    average_tip = ("tip", "mean")
).round(2)
summary

      bill_count  avg_bill  average_tip
day
Fri           19     17.15         2.73
Sat           87     20.44         2.99
Sun           76     21.41         3.26
Thur          62     17.68         2.77

In [33]:
summary = summary.reset_index()
summary

    day  bill_count  avg_bill  average_tip
0   Fri          19     17.15         2.73
1   Sat          87     20.44         2.99
2   Sun          76     21.41         3.26
3  Thur          62     17.68         2.77

In [21]:
summary[summary["average_tip"] >= 3]

     bill_count  avg_bill  average_tip
day
Sun          76     21.41         3.26

In [22]:
summary.columns #in groupby, we dont get column of that value on the basis of which we grouped the data

Index(['bill_count', 'avg_bill', 'average_tip'], dtype='str')

In [36]:
#reset_index()
flat = summary.reset_index()
print(flat.columns.tolist())
flat.head()

['index', 'day', 'bill_count', 'avg_bill', 'average_tip']

   index   day  bill_count  avg_bill  average_tip
0      0   Fri          19     17.15         2.73
1      1   Sat          87     20.44         2.99
2      2   Sun          76     21.41         3.26
3      3  Thur          62     17.68         2.77

In [ ]:
tip.groupby("time").agg(
    bills = ("total_bill", "size"),
    avg_bill = ("total_bill", "mean"),
    avg_party = ("size", "mean")
)

        bills  avg_bill  avg_party
time
Dinner    176     20.80       2.63
Lunch      68     17.17       2.41

In [ ]:
summary.to_csv("report.csv") #new csv file is created to store the data

In [22]:
smoker = tip.groupby("smoker").agg(
    bills = ("total_bill", "size"),
    avg_bill = ("total_bill", "mean"),
    avg_tip = ("tip", "mean")
).round(2)
smoker.reset_index()
smoker.to_csv("smoker.csv")
temp = pd.read_csv("smoker.csv")
temp.head()

  smoker  bills  avg_bill  avg_tip
0     No    151     19.19     2.99
1    Yes     93     20.76     3.01

In [ ]:
#idxmax - returns index label of the row holding the maximum - not the value, the address 
tip.groupby("day")['tip'].idxmax()

day
Fri      95
Sat     170
Sun     183
Thur    141
Name: tip, dtype: int64

In [29]:
tip.groupby("day")['tip'].max()

day
Fri      4.73
Sat     10.00
Sun      6.50
Thur     6.70
Name: tip, dtype: float64

In [ ]:
tip.loc[183] # row ka data deta hai

total_bill     23.17
tip              6.5
sex             Male
smoker           Yes
day              Sun
time          Dinner
size               4
Name: 183, dtype: object

In [33]:
booking = pd.read_csv("booking.csv")
booking

    booking_id        customer  day    time  party_size
0          101     ravi sharma  Sat  Dinner         4.0
1          102      PRIYA IYER  Sat  Dinner         2.0
2          103    Ravi Sharma   Sun   Lunch         NaN
3          104      amit kumar  Sun  Dinner         6.0
4          105     priya  iyer  Fri  Dinner         NaN
5          106     RAVI SHARMA  Sat   Lunch         3.0
6          107       sana khan  Sat   Lunch         NaN
7          108      Amit Kumar  Sat  Dinner         5.0
8          109      vikram rao  Sun  Dinner         2.0
9          110      Sana  Khan  Fri  Dinner         4.0
10         111      priya iyer  Sat   Lunch         NaN
11         112      VIKRAM RAO  Sun   Lunch         3.0

In [34]:
booking['customer'].nunique()

12

In [49]:
#DATA CLEANING
booking["customer"] = booking["customer"].str.lower().str.strip().str.split().str.join(" ")
#.lower - sabhi charcaters ko lower me convert krta hai
#.strip - leading and ending white spaces remove kr rha hai
#.split - string ko list me convert kr rha hai
#.join - list ko final string me convert krne ke liye

In [50]:
booking['customer'].nunique()

5