## INSTALLING PANDAS

In [1]:
! pip3 install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/anugrahpal/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/anugrahpal/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
! pip3 install --upgrade pip

Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (26.2.1)

## PANDAS

In [3]:
import pandas as pd
import numpy as np

In [4]:
# pd.DataFrame() - creates a table from a dictionary 
restaurant_data = {
    'Table_No' : [12, 14, 15],
    'Bill_Amount' : [1250, 890, 2400],
    'Waiter_Name' : ['Amit', 'Priya', 'Rahul']
}

df = pd.DataFrame(restaurant_data)
print(df)
print(type(df))

print(df['Bill_Amount'])
print(type(df['Bill_Amount']))

   Table_No  Bill_Amount Waiter_Name
0        12         1250        Amit
1        14          890       Priya
2        15         2400       Rahul
<class 'pandas.DataFrame'>
0    1250
1     890
2    2400
Name: Bill_Amount, dtype: int64
<class 'pandas.Series'>

In [5]:
# pd.Series - creates Series (1D data with an index)
total_bill = [4700, 6744, 760, 4583]
s = pd.Series(total_bill, index = ['mon', 'tue', 'wed', 'thurs']) #index is used to change 0,1,2,.... to replaced index
print(s)
print(type(s))

mon      4700
tue      6744
wed       760
thurs    4583
dtype: int64
<class 'pandas.Series'>

In [6]:
# .values / .to_numpy() - the NumPy array underneath
print(df.values)
print(type(df.values))

[[12 1250 'Amit']
 [14 890 'Priya']
 [15 2400 'Rahul']]
<class 'numpy.ndarray'>

In [7]:
#Q:
s = [45, 30, 15, 60]
s = pd.Series(s, index = ['PIZZA', 'BURGER', 'PASTA', 'FRIES'])
print(s)

PIZZA     45
BURGER    30
PASTA     15
FRIES     60
dtype: int64

In [8]:
#Q
p = {
    'Brand' : ['Nike', 'Puma', 'Campus'],
    'Price' : [2500, 4000, 8000]
}
df = pd.DataFrame(p)
print(df)

    Brand  Price
0    Nike   2500
1    Puma   4000
2  Campus   8000

In [9]:
# pd.read_csv() - used to read/import a CSV file into a DataFrame
df = pd.read_csv("tip.csv")
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [10]:
# head()
print(df.head())

print()
print()
print()
print(df.head(10))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4



   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [11]:
# tail()
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [12]:
# df.sample() - gives a random value
print(df.sample()) # will give 1 random value
print()
print()
print()
print(df.sample(5)) # will give 5 random values

     total_bill  tip     sex smoker   day   time  size
118       12.43  1.8  Female     No  Thur  Lunch     2



     total_bill   tip     sex smoker   day    time  size
142       41.19  5.00    Male     No  Thur   Lunch     5
39        31.27  5.00    Male     No   Sat  Dinner     3
227       20.45  3.00    Male     No   Sat  Dinner     4
0         16.99  1.01  Female     No   Sun  Dinner     2
83        32.68  5.00    Male    Yes  Thur   Lunch     2

In [13]:
# .shape - gives number of rows and columns
print(df.shape)

# .coulmns - gives list of columns
print(df.columns.tolist())

(244, 7)
['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

In [78]:
# info() - dtypes and null counts in one shot
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [ ]:
# describe() - mathematical analysis of data (statistics)
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
# value_counts(), unique(), nunique()
print(df['day'].value_counts())
print()
print()
print()
print(df['day'].unique())
print()
print()
print()
print(df['day'].nunique())

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64



<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str



4